"""add deals

Revision ID: 669a6c1da626
Revises: fee056829322
Create Date: 2026-08-16 00:50:38.692322

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "669a6c1da626"
down_revision: str | Sequence[str] | None = "fee056829322"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("public_id", sa.String(length=16), nullable=False),
        sa.Column("merchant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("payment_requisite_id", sa.UUID(), nullable=True),
        sa.Column("amount_tjs", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("exchange_rate", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("amount_usdt", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "created",
                "available",
                "accepted",
                "payment_pending",
                "completed",
                "cancelled",
                "expired",
                "disputed",
                name="deal_status",
            ),
            nullable=False,
        ),
        # Reuses the payment_requisite_type ENUM created by the Stage 6
        # migration. create_type=False: the type already exists in the DB
        # from that earlier, already-applied migration - checkfirst only
        # dedupes types created earlier in the *same* migration run, not
        # ones from a prior one, so without this op.create_table would try
        # (and fail) to CREATE TYPE again. Mirrored by create_type=False on
        # drop, so downgrade never touches this shared type either.
        sa.Column(
            "requisite_type",
            postgresql.ENUM("bank_card", name="payment_requisite_type", create_type=False),
            nullable=True,
        ),
        sa.Column("requisite_bank_name", sa.String(length=255), nullable=True),
        sa.Column("requisite_holder_name", sa.String(length=255), nullable=True),
        sa.Column("requisite_masked_card_number", sa.String(length=32), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount_tjs > 0", name="ck_deals_amount_tjs_positive"),
        sa.CheckConstraint(
            "amount_usdt IS NULL OR amount_usdt > 0", name="ck_deals_amount_usdt_positive"
        ),
        sa.CheckConstraint(
            "exchange_rate IS NULL OR exchange_rate > 0", name="ck_deals_exchange_rate_positive"
        ),
        sa.ForeignKeyConstraint(["merchant_id"], ["accounts.id"]),
        sa.ForeignKeyConstraint(["payment_requisite_id"], ["payment_requisites.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["accounts.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_deals_created_at"), "deals", ["created_at"], unique=False)
    op.create_index(op.f("ix_deals_expires_at"), "deals", ["expires_at"], unique=False)
    op.create_index(op.f("ix_deals_merchant_id"), "deals", ["merchant_id"], unique=False)
    op.create_index(op.f("ix_deals_public_id"), "deals", ["public_id"], unique=True)
    op.create_index(op.f("ix_deals_status"), "deals", ["status"], unique=False)
    op.create_index(op.f("ix_deals_user_id"), "deals", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deals_user_id"), table_name="deals")
    op.drop_index(op.f("ix_deals_status"), table_name="deals")
    op.drop_index(op.f("ix_deals_public_id"), table_name="deals")
    op.drop_index(op.f("ix_deals_merchant_id"), table_name="deals")
    op.drop_index(op.f("ix_deals_expires_at"), table_name="deals")
    op.drop_index(op.f("ix_deals_created_at"), table_name="deals")
    op.drop_table("deals")
    # ### end Alembic commands ###

    # Only drop deal_status - it was created by THIS migration. Do NOT drop
    # payment_requisite_type here: it was created by the Stage 6 migration
    # and payment_requisites.type still depends on it.
    sa.Enum(name="deal_status").drop(op.get_bind(), checkfirst=True)
