"""add wallets and ledger entries

Revision ID: 7e1c2f594149
Revises: 9f72b9a4aa6d
Create Date: 2026-08-15 18:18:13.478219

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e1c2f594149"
down_revision: str | Sequence[str] | None = "9f72b9a4aa6d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("currency", sa.Enum("USDT", name="wallet_currency"), nullable=False),
        sa.Column(
            "available_balance",
            sa.Numeric(precision=20, scale=8),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "insurance_balance",
            sa.Numeric(precision=20, scale=8),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "frozen_balance",
            sa.Numeric(precision=20, scale=8),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("available_balance >= 0", name="ck_wallets_available_non_negative"),
        sa.CheckConstraint("frozen_balance >= 0", name="ck_wallets_frozen_non_negative"),
        sa.CheckConstraint("insurance_balance >= 0", name="ck_wallets_insurance_non_negative"),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_wallets_account_id"), "wallets", ["account_id"], unique=True)
    op.create_table(
        "ledger_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "owner_allocation",
                "insurance_adjustment",
                "manual_adjustment",
                "deal_freeze",
                "deal_release",
                "deal_settlement",
                name="ledger_entry_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "balance_bucket",
            sa.Enum("available", "insurance", "frozen", name="ledger_balance_bucket"),
            nullable=False,
        ),
        sa.Column("currency", sa.Enum("USDT", name="wallet_currency"), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("available_before", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("available_after", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("insurance_before", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("insurance_after", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("frozen_before", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("frozen_after", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("reference_type", sa.String(length=50), nullable=True),
        sa.Column("reference_id", sa.UUID(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("created_by_account_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"]),
        sa.ForeignKeyConstraint(["created_by_account_id"], ["accounts.id"]),
        sa.ForeignKeyConstraint(["wallet_id"], ["wallets.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "wallet_id", "idempotency_key", name="uq_ledger_entries_wallet_idempotency_key"
        ),
    )
    op.create_index(
        op.f("ix_ledger_entries_account_id"), "ledger_entries", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_ledger_entries_created_at"), "ledger_entries", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_ledger_entries_type"), "ledger_entries", ["type"], unique=False)
    op.create_index(
        op.f("ix_ledger_entries_wallet_id"), "ledger_entries", ["wallet_id"], unique=False
    )
    # ### end Alembic commands ###

    # Backfill: any pre-existing USER account (created before this stage,
    # e.g. by Stage 4) gets a zero-balance wallet, same as new ones do.
    # MERCHANT/OWNER accounts are untouched. Idempotent - safe to re-run.
    op.execute(
        """
        INSERT INTO wallets (id, account_id, currency, available_balance,
                              insurance_balance, frozen_balance, created_at, updated_at)
        SELECT gen_random_uuid(), accounts.id, 'USDT', 0, 0, 0, now(), now()
        FROM accounts
        WHERE accounts.role = 'user'
          AND NOT EXISTS (
              SELECT 1 FROM wallets WHERE wallets.account_id = accounts.id
          )
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ledger_entries_wallet_id"), table_name="ledger_entries")
    op.drop_index(op.f("ix_ledger_entries_type"), table_name="ledger_entries")
    op.drop_index(op.f("ix_ledger_entries_created_at"), table_name="ledger_entries")
    op.drop_index(op.f("ix_ledger_entries_account_id"), table_name="ledger_entries")
    op.drop_table("ledger_entries")
    op.drop_index(op.f("ix_wallets_account_id"), table_name="wallets")
    op.drop_table("wallets")
    # ### end Alembic commands ###

    # Postgres does not drop ENUM types when their tables are dropped, so a
    # re-run of upgrade() would fail on CREATE TYPE without this (see the
    # same fix in the Stage 2 accounts migration).
    sa.Enum(name="ledger_entry_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="ledger_balance_bucket").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="wallet_currency").drop(op.get_bind(), checkfirst=True)
