"""create accounts table

Revision ID: 9f72b9a4aa6d
Revises: a9d17dd13711
Create Date: 2026-08-15 12:38:49.321309

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f72b9a4aa6d"
down_revision: str | Sequence[str] | None = "a9d17dd13711"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.Enum("owner", "user", "merchant", name="user_role"), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_verified", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone"),
    )
    op.create_index(op.f("ix_accounts_role"), "accounts", ["role"], unique=False)
    op.create_index(op.f("ix_accounts_username"), "accounts", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_accounts_username"), table_name="accounts")
    op.drop_index(op.f("ix_accounts_role"), table_name="accounts")
    op.drop_table("accounts")
    # ### end Alembic commands ###
    # Postgres ENUM types are not dropped automatically when their table is
    # dropped, so a re-run of upgrade() would fail on CREATE TYPE. Drop it
    # explicitly to keep upgrade/downgrade reversible.
    sa.Enum(name="user_role").drop(op.get_bind(), checkfirst=True)
