"""add deposits and deposit credit ledger type

Revision ID: cdd659866190
Revises: 669a6c1da626
Create Date: 2026-08-16 11:22:08.036115

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cdd659866190"
down_revision: str | Sequence[str] | None = "669a6c1da626"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # New LedgerEntryType value for the Stage 8 deposit-credit flow. Safe to
    # run inside this migration's transaction on Postgres 12+ - the new
    # value just isn't usable by an INSERT in this same transaction, and
    # nothing here tries to do that.
    op.execute("ALTER TYPE ledger_entry_type ADD VALUE IF NOT EXISTS 'deposit_credit'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deposits",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("public_id", sa.String(length=16), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("network", sa.Enum("TRC20", name="deposit_network"), nullable=False),
        sa.Column("asset", sa.Enum("USDT", name="deposit_asset"), nullable=False),
        sa.Column("expected_amount", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("received_amount", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("credited_amount", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("deposit_address", sa.String(length=128), nullable=False),
        sa.Column("tx_hash", sa.String(length=128), nullable=True),
        sa.Column("confirmations", sa.Integer(), server_default="0", nullable=False),
        sa.Column("required_confirmations", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "waiting",
                "detected",
                "confirming",
                "confirmed",
                "credited",
                "expired",
                "failed",
                "amount_mismatch",
                name="deposit_status",
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("credited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("confirmations >= 0", name="ck_deposits_confirmations_non_negative"),
        sa.CheckConstraint(
            "credited_amount IS NULL OR credited_amount > 0",
            name="ck_deposits_credited_amount_positive",
        ),
        sa.CheckConstraint("expected_amount > 0", name="ck_deposits_expected_amount_positive"),
        sa.CheckConstraint(
            "received_amount IS NULL OR received_amount > 0",
            name="ck_deposits_received_amount_positive",
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tx_hash"),
    )
    op.create_index(op.f("ix_deposits_account_id"), "deposits", ["account_id"], unique=False)
    op.create_index(op.f("ix_deposits_created_at"), "deposits", ["created_at"], unique=False)
    op.create_index(op.f("ix_deposits_expires_at"), "deposits", ["expires_at"], unique=False)
    op.create_index(op.f("ix_deposits_public_id"), "deposits", ["public_id"], unique=True)
    op.create_index(op.f("ix_deposits_status"), "deposits", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deposits_status"), table_name="deposits")
    op.drop_index(op.f("ix_deposits_public_id"), table_name="deposits")
    op.drop_index(op.f("ix_deposits_expires_at"), table_name="deposits")
    op.drop_index(op.f("ix_deposits_created_at"), table_name="deposits")
    op.drop_index(op.f("ix_deposits_account_id"), table_name="deposits")
    op.drop_table("deposits")
    # ### end Alembic commands ###

    # Only drop types created by THIS migration (deposit_status/network/
    # asset). Postgres has no ALTER TYPE ... DROP VALUE, so the
    # 'deposit_credit' value added to ledger_entry_type above cannot be
    # removed here - it's left in place on downgrade. That's harmless: an
    # unused enum value on a type is not itself a correctness problem.
    sa.Enum(name="deposit_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="deposit_network").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="deposit_asset").drop(op.get_bind(), checkfirst=True)
