"""add payment requisites and traffic settings

Revision ID: fee056829322
Revises: 7e1c2f594149
Create Date: 2026-08-15 22:56:01.812469

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fee056829322'
down_revision: str | Sequence[str] | None = '7e1c2f594149'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'payment_requisites',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('account_id', sa.UUID(), nullable=False),
        sa.Column('type', sa.Enum('bank_card', name='payment_requisite_type'), nullable=False),
        sa.Column('bank_name', sa.String(length=255), nullable=False),
        sa.Column('holder_name', sa.String(length=255), nullable=False),
        sa.Column('card_number', sa.String(length=32), nullable=False),
        sa.Column('phone_number', sa.String(length=32), nullable=True),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
        sa.Column(
            'created_at', sa.DateTime(timezone=True),
            server_default=sa.text('now()'), nullable=False,
        ),
        sa.Column(
            'updated_at', sa.DateTime(timezone=True),
            server_default=sa.text('now()'), nullable=False,
        ),
        sa.CheckConstraint("card_number <> ''", name='ck_payment_requisites_card_number_not_empty'),
        sa.CheckConstraint(
            'NOT (is_archived AND is_active)', name='ck_payment_requisites_archived_not_active'
        ),
        sa.ForeignKeyConstraint(['account_id'], ['accounts.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_payment_requisites_account_id'), 'payment_requisites', ['account_id'],
        unique=False,
    )
    op.create_index(
        'uq_payment_requisites_account_card_non_archived', 'payment_requisites',
        ['account_id', 'card_number'], unique=True,
        postgresql_where=sa.text('NOT is_archived'),
    )
    op.create_table(
        'user_traffic_settings',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('account_id', sa.UUID(), nullable=False),
        sa.Column('is_enabled', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('enabled_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'created_at', sa.DateTime(timezone=True),
            server_default=sa.text('now()'), nullable=False,
        ),
        sa.Column(
            'updated_at', sa.DateTime(timezone=True),
            server_default=sa.text('now()'), nullable=False,
        ),
        sa.ForeignKeyConstraint(['account_id'], ['accounts.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_user_traffic_settings_account_id'), 'user_traffic_settings', ['account_id'],
        unique=True,
    )
    # ### end Alembic commands ###

    # Backfill: any pre-existing USER account without traffic settings yet
    # gets Traffic OFF, same as new ones do. MERCHANT/OWNER are untouched.
    # Idempotent - safe to re-run.
    op.execute(
        """
        INSERT INTO user_traffic_settings (id, account_id, is_enabled, created_at, updated_at)
        SELECT gen_random_uuid(), accounts.id, false, now(), now()
        FROM accounts
        WHERE accounts.role = 'user'
          AND NOT EXISTS (
              SELECT 1 FROM user_traffic_settings
              WHERE user_traffic_settings.account_id = accounts.id
          )
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_traffic_settings_account_id'), table_name='user_traffic_settings')
    op.drop_table('user_traffic_settings')
    op.drop_index(
        'uq_payment_requisites_account_card_non_archived', table_name='payment_requisites',
        postgresql_where=sa.text('NOT is_archived'),
    )
    op.drop_index(op.f('ix_payment_requisites_account_id'), table_name='payment_requisites')
    op.drop_table('payment_requisites')
    # ### end Alembic commands ###

    # Postgres does not drop ENUM types when their table is dropped, so a
    # re-run of upgrade() would fail on CREATE TYPE without this (same fix
    # as the Stage 2 and Stage 5 migrations).
    sa.Enum(name='payment_requisite_type').drop(op.get_bind(), checkfirst=True)
