from enum import StrEnum


class NotificationChannel(StrEnum):
    TELEGRAM = "TELEGRAM"
    IN_APP = "IN_APP"


class NotificationType(StrEnum):
    DEAL_CREATED = "DEAL_CREATED"
    DEAL_ACCEPTED = "DEAL_ACCEPTED"
    DEAL_PAID = "DEAL_PAID"
    DEAL_COMPLETED = "DEAL_COMPLETED"
    DEAL_CANCELLED = "DEAL_CANCELLED"
    APPEAL_OPENED = "APPEAL_OPENED"
    APPEAL_RESOLVED = "APPEAL_RESOLVED"
    DEPOSIT_CONFIRMED = "DEPOSIT_CONFIRMED"
    WITHDRAWAL_STATUS_CHANGED = "WITHDRAWAL_STATUS_CHANGED"


class NotificationStatus(StrEnum):
    PENDING = "PENDING"
    SENT = "SENT"
    FAILED = "FAILED"
