"use client";

import { useState } from "react";
import { useTranslations } from "next-intl";
import { useAppFormat } from "@/features/i18n/use-app-format";
import { analyticsApi, type DealTimeSeriesPoint } from "@/lib/api/analytics";
import { useApiQuery } from "@/lib/hooks/use-api-query";
import { Heading } from "../owner-components";
import ownerStyles from "../owner.module.css";
import styles from "./analytics.module.css";

type Period = "today" | "7d" | "30d" | "90d";

export default function OwnerAnalyticsPage() {
  const t = useTranslations("analytics");
  const format = useAppFormat();
  const [period, setPeriod] = useState<Period>("30d");
  const query = useApiQuery(() => analyticsApi.bundle(period), `analytics:${period}`);
  const data = query.data;
  return <section><div className={styles.header}><Heading title={t("title")} text={t("subtitle")} /><label className={styles.period}><select aria-label={t("period")} value={period} onChange={(event) => setPeriod(event.target.value as Period)}><option value="today">{t("today")}</option><option value="7d">{t("days", { count: 7 })}</option><option value="30d">{t("days", { count: 30 })}</option><option value="90d">{t("days", { count: 90 })}</option></select></label></div>{query.loading ? <div className={ownerStyles.state}>{t("loading")}</div> : query.error ? <div className={ownerStyles.error}>{query.error}</div> : data && <><div className={ownerStyles.kpiGrid}><K label={t("totalDeals")} value={format.number(data.deals.total_deals)} /><K label={t("completed")} value={format.number(data.deals.completed_deals)} /><K label={t("completionRate")} value={`${format.number(data.deals.completion_rate, 2)}%`} /><K label={t("disputeRate")} value={`${format.number(data.deals.dispute_rate, 2)}%`} /></div><div className={styles.metrics}><Metric label={t("volumeTjs")} value={format.number(data.deals.total_volume_tjs)} unit="TJS" /><Metric label={t("volumeUsdt")} value={format.number(data.deals.total_volume_usdt)} /><Metric label={t("depositsCredited")} value={format.number(data.flow.deposits_credited_usdt)} /><Metric label={t("withdrawalsPaid")} value={format.number(data.flow.withdrawals_paid_usdt)} /></div><TimeSeriesChart points={data.timeseries} emptyLabel={t("chartEmpty")} title={t("dealsTrend")} dealsLabel={t("totalDeals")} completedLabel={t("completed")} /><div className={styles.lower}><article className={styles.panel}><span className={styles.eyebrow}>{t("accountsEyebrow")}</span><h2>{t("accounts")}</h2><div className={styles.rows}><Row label={t("activeUsers")} value={format.number(data.accounts.users_active)} /><Row label={t("activeMerchants")} value={format.number(data.accounts.merchants_active)} /><Row label={t("trafficEnabled")} value={format.number(data.accounts.traffic_enabled_users)} /></div></article><article className={styles.panel}><span className={styles.eyebrow}>{t("integrityEyebrow")}</span><h2>{t("integrity")}</h2><div className={styles.rows}><Row label={t("userWallets")} value={format.number(data.integrity.user_wallet_total_usdt)} unit="USDT" /><Row label={t("merchantWallets")} value={format.number(data.integrity.merchant_wallet_total_usdt)} unit="USDT" /></div><span className={styles.status}>{t(`integrityStatus.${data.integrity.status}`)}</span></article></div></>}</section>;
}

function K({ label, value }: { label: string; value: string }) { return <div className={ownerStyles.kpi}><span>{label}</span><strong>{value}</strong></div>; }
function Metric({ label, value, unit = "USDT" }: { label: string; value: string; unit?: string }) { return <article className={styles.metric}><span>{label}</span><div><strong>{value}</strong><small>{unit}</small></div></article>; }
function Row({ label, value, unit }: { label: string; value: string; unit?: string }) { return <div className={styles.row}><span>{label}</span><div><strong>{value}</strong>{unit && <small>{unit}</small>}</div></div>; }
function TimeSeriesChart({ points, emptyLabel, title, dealsLabel, completedLabel }: { points: DealTimeSeriesPoint[]; emptyLabel: string; title: string; dealsLabel: string; completedLabel: string }) { const max = Math.max(0, ...points.flatMap((point) => [point.deals, point.completed])); const path = (field: "deals" | "completed") => points.map((point, index) => `${index ? "L" : "M"} ${points.length === 1 ? 50 : (index / (points.length - 1)) * 100} ${100 - (max ? point[field] / max * 90 : 0)}`).join(" "); return <article className={`${styles.panel} ${styles.chart}`}><div className={styles.chartHeader}><div><span className={styles.eyebrow}>{title}</span><h2>{title}</h2></div><div className={styles.legend}><span><i />{dealsLabel}</span><span><i />{completedLabel}</span></div></div>{!points.length ? <div className={styles.empty}>{emptyLabel}</div> : <svg className={styles.plot} viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label={title}><line className={styles.gridLine} x1="0" y1="10" x2="100" y2="10" /><line className={styles.gridLine} x1="0" y1="55" x2="100" y2="55" /><line className={styles.gridLine} x1="0" y1="100" x2="100" y2="100" /><path className={styles.dealsLine} d={path("deals")} /><path className={styles.completedLine} d={path("completed")} /></svg>}</article>; }
