"use client";

import { useEffect, useState } from "react";
import { useTranslations } from "next-intl";

import { Pager } from "@/components/ui/pager";
import { useAppFormat } from "@/features/i18n/use-app-format";
import { useLocalizedError } from "@/features/i18n/use-localized-error";
import { ownerOperationsApi } from "@/lib/api/owner-operations";
import type { PayoutIntent, PayoutPolicyInput, PayoutStatus } from "@/lib/api/types";
import { useApiQuery } from "@/lib/hooks/use-api-query";
import { Heading } from "../owner-components";
import styles from "./payouts.module.css";

const statuses: PayoutStatus[] = ["risk_review", "approved", "queued", "execution_pending", "executing", "reconciliation_required", "succeeded", "failed", "rejected", "cancelled", "awaiting_manual_settlement"];
const defaults: PayoutPolicyInput = { payouts_enabled: false, auto_approval_enabled: false, default_required_approvals: 1, dual_approval_threshold_usdt: null, high_value_required_approvals: 2, max_single_payout_enabled: false, max_single_payout_usdt: null, max_daily_payout_enabled: false, max_daily_payout_usdt: null, max_hourly_payout_enabled: false, max_hourly_payout_usdt: null, max_pending_payout_enabled: false, max_pending_payout_usdt: null, max_asset_exposure_enabled: false, max_asset_exposure_usdt: null };

export default function OwnerPayoutsPage() {
  const t = useTranslations("payouts"); const common = useTranslations("common");
  const format = useAppFormat(); const localizeError = useLocalizedError();
  const [status, setStatus] = useState<PayoutStatus | "">(""); const [offset, setOffset] = useState(0);
  const query = useApiQuery(() => ownerOperationsApi.payouts(status || undefined, offset), `owner-payouts:${status}:${offset}`);
  const policy = useApiQuery(ownerOperationsApi.payoutPolicy, "payout-policy");
  const [form, setForm] = useState<PayoutPolicyInput>(defaults); const [draft, setDraft] = useState<string | null>(null);
  const [detail, setDetail] = useState<PayoutIntent | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const [manualRef, setManualRef] = useState(""); const [evidence, setEvidence] = useState("");
  useEffect(() => { if (policy.data) { const timer = window.setTimeout(() => setForm({ ...defaults, ...policy.data }), 0); return () => window.clearTimeout(timer); } }, [policy.data]);
  async function open(id: string) { setError(""); try { setDetail(await ownerOperationsApi.payout(id)); } catch (e) { setError(localizeError(e)); } }
  async function run(action: () => Promise<PayoutIntent>) { setBusy(true); setError(""); try { const item = await action(); setDetail(item); await query.refetch(); } catch (e) { setError(localizeError(e)); } finally { setBusy(false); } }
  async function createPolicy() { setBusy(true); setError(""); try { const value = await ownerOperationsApi.createPayoutPolicy(form); setDraft(value.id); } catch (e) { setError(localizeError(e)); } finally { setBusy(false); } }
  async function activatePolicy() { if (!draft) return; setBusy(true); try { await ownerOperationsApi.activatePayoutPolicy(draft); setDraft(null); await policy.refetch(); } catch (e) { setError(localizeError(e)); } finally { setBusy(false); } }
  const set = <K extends keyof PayoutPolicyInput>(key: K, value: PayoutPolicyInput[K]) => { setForm((old) => ({ ...old, [key]: value })); setDraft(null); };
  return <section><Heading title={t("title")} text={t("subtitle")} />
    <div className={styles.safety}><strong>{t("safetyTitle")}</strong><span>{t("safetyText")}</span></div>
    <div className={styles.toolbar}><select value={status} aria-label={common("status")} onChange={(e) => { setStatus(e.target.value as PayoutStatus | ""); setOffset(0); }}><option value="">{common("allStatuses")}</option>{statuses.map((value) => <option value={value} key={value}>{t(`statuses.${value}`)}</option>)}</select><span>{policy.data?.payouts_enabled ? t("businessEnabled") : t("businessDisabled")}</span></div>
    {(error || query.error) && <div className={styles.error}>{error || query.error}</div>}
    <div className={styles.card}>{query.loading ? <div className={styles.state}>{common("loading")}</div> : !query.data?.items.length ? <div className={styles.state}>{common("noData")}</div> : <div className={styles.table}><table><thead><tr><th>{t("intent")}</th><th>{common("amount")}</th><th>{t("destination")}</th><th>{t("risk")}</th><th>{t("approval")}</th><th>{common("status")}</th></tr></thead><tbody>{query.data.items.map((item) => <tr key={item.id} onClick={() => void open(item.id)}><td><strong>{item.id.slice(0, 8)}</strong><small>{format.dateTime(item.created_at)}</small></td><td>{format.number(item.amount, 8)} {item.asset}</td><td>{item.network}<small>{item.masked_destination}</small></td><td>{item.risk_decision}<small>v{item.risk_policy_version}</small></td><td>{item.approval_count}/{item.required_approvals}</td><td><span data-status={item.status}>{t(`statuses.${item.status}`)}</span></td></tr>)}</tbody></table></div>}{query.data && <Pager offset={offset} limit={20} itemCount={query.data.items.length} total={query.data.total} onPage={setOffset} />}</div>
    <article className={styles.policy}><h2>{t("policy")}</h2><p>{t("policyHint")}</p><Toggle label={t("businessSwitch")} checked={form.payouts_enabled} onChange={(v) => set("payouts_enabled", v)} /><div className={styles.fields}><NumberField label={t("baseApprovals")} value={String(form.default_required_approvals)} onChange={(v) => set("default_required_approvals", Number(v))} /><NumberField label={t("dualThreshold")} value={form.dual_approval_threshold_usdt || ""} onChange={(v) => set("dual_approval_threshold_usdt", v || null)} /><NumberField label={t("highApprovals")} value={String(form.high_value_required_approvals)} onChange={(v) => set("high_value_required_approvals", Number(v))} /></div>{[["max_single_payout_enabled", "max_single_payout_usdt", "maxSingle"], ["max_daily_payout_enabled", "max_daily_payout_usdt", "maxDaily"], ["max_hourly_payout_enabled", "max_hourly_payout_usdt", "maxHourly"], ["max_pending_payout_enabled", "max_pending_payout_usdt", "maxPending"], ["max_asset_exposure_enabled", "max_asset_exposure_usdt", "maxAsset"]].map(([enabled, limit, label]) => <div className={styles.rule} key={enabled}><Toggle label={t(label)} checked={Boolean(form[enabled as keyof PayoutPolicyInput])} onChange={(v) => set(enabled as keyof PayoutPolicyInput, v as never)} /><input type="number" min="0" step="0.00000001" value={(form[limit as keyof PayoutPolicyInput] as string | null) || ""} onChange={(e) => set(limit as keyof PayoutPolicyInput, (e.target.value || null) as never)} /></div>)}<div className={styles.actions}><button disabled={busy} onClick={() => void createPolicy()}>{t("createDraft")}</button><button disabled={busy || !draft} onClick={() => void activatePolicy()}>{t("activate")}</button></div></article>
    {detail && <div className={styles.backdrop} onMouseDown={() => setDetail(null)}><div className={styles.modal} onMouseDown={(e) => e.stopPropagation()}><header><h2>{t("detail")}</h2><button onClick={() => setDetail(null)}>×</button></header><div className={styles.detail}><span>{t("withdrawal")}: {detail.withdrawal_id}</span><span>{format.number(detail.amount, 8)} {detail.asset}</span><span>{detail.network} · {detail.masked_destination}</span><span>{t("provider")}: {detail.provider_mode}</span><span>{t("treasuryAt")}: {format.dateTime(detail.treasury_generated_at)}</span><span>{t("approval")}: {detail.approval_count}/{detail.required_approvals}</span></div><div className={styles.actions}>{detail.status === "risk_review" && <><button disabled={busy} onClick={() => void run(() => ownerOperationsApi.approvePayout(detail.id))}>{t("approve")}</button><button disabled={busy} onClick={() => void run(() => ownerOperationsApi.rejectPayout(detail.id))}>{t("reject")}</button></>}{detail.status === "approved" && <><button disabled={busy} onClick={() => void run(() => ownerOperationsApi.queuePayout(detail.id, "succeeded"))}>{t("queueSuccess")}</button><button disabled={busy} onClick={() => void run(() => ownerOperationsApi.queuePayout(detail.id, "unknown"))}>{t("queueUnknown")}</button><button disabled={busy} onClick={() => void run(() => ownerOperationsApi.beginManualPayout(detail.id))}>{t("manual")}</button></>}{["risk_review", "approved", "queued", "execution_pending", "awaiting_manual_settlement"].includes(detail.status) && <button disabled={busy} onClick={() => void run(() => ownerOperationsApi.cancelPayout(detail.id))}>{common("cancel")}</button>}{["reconciliation_required", "execution_pending"].includes(detail.status) && <button disabled={busy} onClick={() => void run(() => ownerOperationsApi.reconcilePayout(detail.id, "succeeded"))}>{t("reconcile")}</button>}</div>{detail.status === "awaiting_manual_settlement" && <div className={styles.manual}><input value={manualRef} onChange={(e) => setManualRef(e.target.value)} placeholder={t("externalRef")} /><textarea value={evidence} onChange={(e) => setEvidence(e.target.value)} placeholder={t("evidence")} /><button disabled={busy || !manualRef || !evidence} onClick={() => void run(() => ownerOperationsApi.completeManualPayout(detail.id, manualRef, evidence))}>{t("confirmManual")}</button></div>}<h3>{t("timeline")}</h3><div className={styles.timeline}>{detail.events.map((event) => <div key={event.id}><strong>{t.has(`events.${event.event}`) ? t(`events.${event.event}`) : event.event}</strong><small>{format.dateTime(event.created_at)}</small></div>)}</div></div></div>}
  </section>;
}

function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className={styles.toggle}><input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} /><span>{label}</span></label>; }
function NumberField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label><span>{label}</span><input type="number" min="0" value={value} onChange={(e) => onChange(e.target.value)} /></label>; }
